//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 

namespace KeePassKey.Model
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PasswordFont
    {

        private string familyField;

        private string sizeField;

        private string graphicsUnitField;

        private string overrideUIDefaultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GraphicsUnit
        {
            get
            {
                return this.graphicsUnitField;
            }
            set
            {
                this.graphicsUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OverrideUIDefault
        {
            get
            {
                return this.overrideUIDefaultField;
            }
            set
            {
                this.overrideUIDefaultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Configuration
    {

        private string loggingField;

        private string nativeField;

        private string customField;

        private ConfigurationMeta[] metaField;

        private ConfigurationApplication[] applicationField;

        private ConfigurationMainWindow[] mainWindowField;

        private ConfigurationUI[] uiField;

        private ConfigurationSecurity[] securityField;

        private ConfigurationPasswordGenerator[] passwordGeneratorField;

        private ConfigurationSearch[] searchField;

        private ConfigurationDefaults[] defaultsField;

        private ConfigurationIntegration[] integrationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Logging
        {
            get
            {
                return this.loggingField;
            }
            set
            {
                this.loggingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Native
        {
            get
            {
                return this.nativeField;
            }
            set
            {
                this.nativeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Custom
        {
            get
            {
                return this.customField;
            }
            set
            {
                this.customField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Meta", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationMeta[] Meta
        {
            get
            {
                return this.metaField;
            }
            set
            {
                this.metaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Application", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationApplication[] Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MainWindow", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationMainWindow[] MainWindow
        {
            get
            {
                return this.mainWindowField;
            }
            set
            {
                this.mainWindowField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UI", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationUI[] UI
        {
            get
            {
                return this.uiField;
            }
            set
            {
                this.uiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Security", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationSecurity[] Security
        {
            get
            {
                return this.securityField;
            }
            set
            {
                this.securityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PasswordGenerator", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationPasswordGenerator[] PasswordGenerator
        {
            get
            {
                return this.passwordGeneratorField;
            }
            set
            {
                this.passwordGeneratorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Search", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationSearch[] Search
        {
            get
            {
                return this.searchField;
            }
            set
            {
                this.searchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Defaults", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationDefaults[] Defaults
        {
            get
            {
                return this.defaultsField;
            }
            set
            {
                this.defaultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Integration", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationIntegration[] Integration
        {
            get
            {
                return this.integrationField;
            }
            set
            {
                this.integrationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationMeta
    {

        private string versionField;

        private string preferUserConfigurationField;

        private string omitItemsWithDefaultValuesField;

        private string dpiFactorXField;

        private string dpiFactorYField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PreferUserConfiguration
        {
            get
            {
                return this.preferUserConfigurationField;
            }
            set
            {
                this.preferUserConfigurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OmitItemsWithDefaultValues
        {
            get
            {
                return this.omitItemsWithDefaultValuesField;
            }
            set
            {
                this.omitItemsWithDefaultValuesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DpiFactorX
        {
            get
            {
                return this.dpiFactorXField;
            }
            set
            {
                this.dpiFactorXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DpiFactorY
        {
            get
            {
                return this.dpiFactorYField;
            }
            set
            {
                this.dpiFactorYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationApplication
    {

        private string fileOpeningField;

        private string fileClosingField;

        private string pluginCompatibilityField;

        private ConfigurationApplicationLastUsedFile[] lastUsedFileField;

        private ConfigurationApplicationMostRecentlyUsed[] mostRecentlyUsedField;

        private ConfigurationApplicationWorkingDirectories[] workingDirectoriesField;

        private ConfigurationApplicationStart[] startField;

        private ConfigurationApplicationTriggerSystem[] triggerSystemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileOpening
        {
            get
            {
                return this.fileOpeningField;
            }
            set
            {
                this.fileOpeningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileClosing
        {
            get
            {
                return this.fileClosingField;
            }
            set
            {
                this.fileClosingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PluginCompatibility
        {
            get
            {
                return this.pluginCompatibilityField;
            }
            set
            {
                this.pluginCompatibilityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LastUsedFile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationApplicationLastUsedFile[] LastUsedFile
        {
            get
            {
                return this.lastUsedFileField;
            }
            set
            {
                this.lastUsedFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MostRecentlyUsed", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationApplicationMostRecentlyUsed[] MostRecentlyUsed
        {
            get
            {
                return this.mostRecentlyUsedField;
            }
            set
            {
                this.mostRecentlyUsedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkingDirectories", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationApplicationWorkingDirectories[] WorkingDirectories
        {
            get
            {
                return this.workingDirectoriesField;
            }
            set
            {
                this.workingDirectoriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Start", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationApplicationStart[] Start
        {
            get
            {
                return this.startField;
            }
            set
            {
                this.startField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TriggerSystem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationApplicationTriggerSystem[] TriggerSystem
        {
            get
            {
                return this.triggerSystemField;
            }
            set
            {
                this.triggerSystemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationApplicationLastUsedFile
    {

        private string pathField;

        private string credProtModeField;

        private string credSaveModeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CredProtMode
        {
            get
            {
                return this.credProtModeField;
            }
            set
            {
                this.credProtModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CredSaveMode
        {
            get
            {
                return this.credSaveModeField;
            }
            set
            {
                this.credSaveModeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationApplicationMostRecentlyUsed
    {

        private string maxItemCountField;

        private ConfigurationApplicationMostRecentlyUsedItemsConnectionInfo[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaxItemCount
        {
            get
            {
                return this.maxItemCountField;
            }
            set
            {
                this.maxItemCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ConnectionInfo", typeof(ConfigurationApplicationMostRecentlyUsedItemsConnectionInfo), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ConfigurationApplicationMostRecentlyUsedItemsConnectionInfo[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationApplicationMostRecentlyUsedItemsConnectionInfo
    {

        private string pathField;

        private string credProtModeField;

        private string credSaveModeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CredProtMode
        {
            get
            {
                return this.credProtModeField;
            }
            set
            {
                this.credProtModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CredSaveMode
        {
            get
            {
                return this.credSaveModeField;
            }
            set
            {
                this.credSaveModeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationApplicationWorkingDirectories
    {

        private string itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationApplicationStart
    {

        private string checkForUpdateField;

        private string checkForUpdateConfiguredField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckForUpdate
        {
            get
            {
                return this.checkForUpdateField;
            }
            set
            {
                this.checkForUpdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckForUpdateConfigured
        {
            get
            {
                return this.checkForUpdateConfiguredField;
            }
            set
            {
                this.checkForUpdateConfiguredField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationApplicationTriggerSystem
    {

        private string triggersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Triggers
        {
            get
            {
                return this.triggersField;
            }
            set
            {
                this.triggersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationMainWindow
    {

        private string xField;

        private string yField;

        private string widthField;

        private string heightField;

        private string splitterHorizontalFracField;

        private string splitterVerticalFracField;

        private string toolBarField;

        private string entryViewField;

        private string tanViewField;

        private string entryListColumnDisplayOrderField;

        private ConfigurationMainWindowEntryListColumnCollectionColumn[] entryListColumnCollectionField;

        private ConfigurationMainWindowListSorting[] listSortingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SplitterHorizontalFrac
        {
            get
            {
                return this.splitterHorizontalFracField;
            }
            set
            {
                this.splitterHorizontalFracField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SplitterVerticalFrac
        {
            get
            {
                return this.splitterVerticalFracField;
            }
            set
            {
                this.splitterVerticalFracField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ToolBar
        {
            get
            {
                return this.toolBarField;
            }
            set
            {
                this.toolBarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntryView
        {
            get
            {
                return this.entryViewField;
            }
            set
            {
                this.entryViewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TanView
        {
            get
            {
                return this.tanViewField;
            }
            set
            {
                this.tanViewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntryListColumnDisplayOrder
        {
            get
            {
                return this.entryListColumnDisplayOrderField;
            }
            set
            {
                this.entryListColumnDisplayOrderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Column", typeof(ConfigurationMainWindowEntryListColumnCollectionColumn), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ConfigurationMainWindowEntryListColumnCollectionColumn[] EntryListColumnCollection
        {
            get
            {
                return this.entryListColumnCollectionField;
            }
            set
            {
                this.entryListColumnCollectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListSorting", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationMainWindowListSorting[] ListSorting
        {
            get
            {
                return this.listSortingField;
            }
            set
            {
                this.listSortingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationMainWindowEntryListColumnCollectionColumn
    {

        private string typeField;

        private string widthField;

        private string hideWithAsterisksField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HideWithAsterisks
        {
            get
            {
                return this.hideWithAsterisksField;
            }
            set
            {
                this.hideWithAsterisksField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationMainWindowListSorting
    {

        private string orderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationUI
    {

        private string trayIconField;

        private string bannerStyleField;

        private string uIFlagsField;

        private string keyCreationFlagsField;

        private string keyPromptFlagsField;

        private ConfigurationUIHiding[] hidingField;

        private ConfigurationUIStandardFont[] standardFontField;

        private PasswordFont[] passwordFontField;

        private ConfigurationUIDataEditorFont[] dataEditorFontField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrayIcon
        {
            get
            {
                return this.trayIconField;
            }
            set
            {
                this.trayIconField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BannerStyle
        {
            get
            {
                return this.bannerStyleField;
            }
            set
            {
                this.bannerStyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UIFlags
        {
            get
            {
                return this.uIFlagsField;
            }
            set
            {
                this.uIFlagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KeyCreationFlags
        {
            get
            {
                return this.keyCreationFlagsField;
            }
            set
            {
                this.keyCreationFlagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KeyPromptFlags
        {
            get
            {
                return this.keyPromptFlagsField;
            }
            set
            {
                this.keyPromptFlagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Hiding", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationUIHiding[] Hiding
        {
            get
            {
                return this.hidingField;
            }
            set
            {
                this.hidingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StandardFont", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationUIStandardFont[] StandardFont
        {
            get
            {
                return this.standardFontField;
            }
            set
            {
                this.standardFontField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PasswordFont")]
        public PasswordFont[] PasswordFont
        {
            get
            {
                return this.passwordFontField;
            }
            set
            {
                this.passwordFontField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DataEditorFont", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationUIDataEditorFont[] DataEditorFont
        {
            get
            {
                return this.dataEditorFontField;
            }
            set
            {
                this.dataEditorFontField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationUIHiding
    {

        private string hideInEntryWindowField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HideInEntryWindow
        {
            get
            {
                return this.hideInEntryWindowField;
            }
            set
            {
                this.hideInEntryWindowField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationUIStandardFont
    {

        private string familyField;

        private string sizeField;

        private string graphicsUnitField;

        private string overrideUIDefaultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GraphicsUnit
        {
            get
            {
                return this.graphicsUnitField;
            }
            set
            {
                this.graphicsUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OverrideUIDefault
        {
            get
            {
                return this.overrideUIDefaultField;
            }
            set
            {
                this.overrideUIDefaultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationUIDataEditorFont
    {

        private string familyField;

        private string sizeField;

        private string graphicsUnitField;

        private string overrideUIDefaultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GraphicsUnit
        {
            get
            {
                return this.graphicsUnitField;
            }
            set
            {
                this.graphicsUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OverrideUIDefault
        {
            get
            {
                return this.overrideUIDefaultField;
            }
            set
            {
                this.overrideUIDefaultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationSecurity
    {

        private string policyField;

        private ConfigurationSecurityWorkspaceLocking[] workspaceLockingField;

        private ConfigurationSecurityMasterPassword[] masterPasswordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Policy
        {
            get
            {
                return this.policyField;
            }
            set
            {
                this.policyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkspaceLocking", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationSecurityWorkspaceLocking[] WorkspaceLocking
        {
            get
            {
                return this.workspaceLockingField;
            }
            set
            {
                this.workspaceLockingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MasterPassword", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationSecurityMasterPassword[] MasterPassword
        {
            get
            {
                return this.masterPasswordField;
            }
            set
            {
                this.masterPasswordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationSecurityWorkspaceLocking
    {

        private string lockAfterTimeField;

        private string lockAfterGlobalTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LockAfterTime
        {
            get
            {
                return this.lockAfterTimeField;
            }
            set
            {
                this.lockAfterTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LockAfterGlobalTime
        {
            get
            {
                return this.lockAfterGlobalTimeField;
            }
            set
            {
                this.lockAfterGlobalTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationSecurityMasterPassword
    {

        private string minimumLengthField;

        private string minimumQualityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinimumLength
        {
            get
            {
                return this.minimumLengthField;
            }
            set
            {
                this.minimumLengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinimumQuality
        {
            get
            {
                return this.minimumQualityField;
            }
            set
            {
                this.minimumQualityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationPasswordGenerator
    {

        private string userProfilesField;

        private ConfigurationPasswordGeneratorAutoGeneratedPasswordsProfile[] autoGeneratedPasswordsProfileField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserProfiles
        {
            get
            {
                return this.userProfilesField;
            }
            set
            {
                this.userProfilesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AutoGeneratedPasswordsProfile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationPasswordGeneratorAutoGeneratedPasswordsProfile[] AutoGeneratedPasswordsProfile
        {
            get
            {
                return this.autoGeneratedPasswordsProfileField;
            }
            set
            {
                this.autoGeneratedPasswordsProfileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationPasswordGeneratorAutoGeneratedPasswordsProfile
    {

        private string generatorTypeField;

        private string lengthField;

        private string charSetRangesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeneratorType
        {
            get
            {
                return this.generatorTypeField;
            }
            set
            {
                this.generatorTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CharSetRanges
        {
            get
            {
                return this.charSetRangesField;
            }
            set
            {
                this.charSetRangesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationSearch
    {

        private string userProfilesField;

        private ConfigurationSearchLastUsedProfile[] lastUsedProfileField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserProfiles
        {
            get
            {
                return this.userProfilesField;
            }
            set
            {
                this.userProfilesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LastUsedProfile", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationSearchLastUsedProfile[] LastUsedProfile
        {
            get
            {
                return this.lastUsedProfileField;
            }
            set
            {
                this.lastUsedProfileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationSearchLastUsedProfile
    {

        private string searchModeField;

        private string comparisonModeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SearchMode
        {
            get
            {
                return this.searchModeField;
            }
            set
            {
                this.searchModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ComparisonMode
        {
            get
            {
                return this.comparisonModeField;
            }
            set
            {
                this.comparisonModeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationDefaults
    {

        private string optionsTabIndexField;

        private string duplicationField;

        private ConfigurationDefaultsKeySourcesAssociation[] keySourcesField;

        private ConfigurationDefaultsPrint[] printField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionsTabIndex
        {
            get
            {
                return this.optionsTabIndexField;
            }
            set
            {
                this.optionsTabIndexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Duplication
        {
            get
            {
                return this.duplicationField;
            }
            set
            {
                this.duplicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Association", typeof(ConfigurationDefaultsKeySourcesAssociation), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ConfigurationDefaultsKeySourcesAssociation[] KeySources
        {
            get
            {
                return this.keySourcesField;
            }
            set
            {
                this.keySourcesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Print", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationDefaultsPrint[] Print
        {
            get
            {
                return this.printField;
            }
            set
            {
                this.printField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationDefaultsKeySourcesAssociation
    {

        private string databasePathField;

        private string passwordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DatabasePath
        {
            get
            {
                return this.databasePathField;
            }
            set
            {
                this.databasePathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationDefaultsPrint
    {

        private ConfigurationDefaultsPrintMainFont[] mainFontField;

        private PasswordFont[] passwordFontField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MainFont", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationDefaultsPrintMainFont[] MainFont
        {
            get
            {
                return this.mainFontField;
            }
            set
            {
                this.mainFontField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PasswordFont")]
        public PasswordFont[] PasswordFont
        {
            get
            {
                return this.passwordFontField;
            }
            set
            {
                this.passwordFontField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationDefaultsPrintMainFont
    {

        private string familyField;

        private string sizeField;

        private string graphicsUnitField;

        private string overrideUIDefaultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GraphicsUnit
        {
            get
            {
                return this.graphicsUnitField;
            }
            set
            {
                this.graphicsUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OverrideUIDefault
        {
            get
            {
                return this.overrideUIDefaultField;
            }
            set
            {
                this.overrideUIDefaultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationIntegration
    {

        private string autoTypeAbortOnWindowsField;

        private ConfigurationIntegrationUrlSchemeOverrides[] urlSchemeOverridesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AutoTypeAbortOnWindows
        {
            get
            {
                return this.autoTypeAbortOnWindowsField;
            }
            set
            {
                this.autoTypeAbortOnWindowsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UrlSchemeOverrides", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfigurationIntegrationUrlSchemeOverrides[] UrlSchemeOverrides
        {
            get
            {
                return this.urlSchemeOverridesField;
            }
            set
            {
                this.urlSchemeOverridesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ConfigurationIntegrationUrlSchemeOverrides
    {

        private string builtInOverridesEnabledField;

        private string customOverridesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BuiltInOverridesEnabled
        {
            get
            {
                return this.builtInOverridesEnabledField;
            }
            set
            {
                this.builtInOverridesEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomOverrides
        {
            get
            {
                return this.customOverridesField;
            }
            set
            {
                this.customOverridesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Configuration", typeof(Configuration))]
        [System.Xml.Serialization.XmlElementAttribute("PasswordFont", typeof(PasswordFont))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

}